# Generated by Django 4.1.7 on 2023-03-06 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_expiring_link', models.BooleanField(default=False, verbose_name='Expiring link')),
                ('is_original_file', models.BooleanField(default=False, verbose_name='Original file')),
                ('thumbnail_size', models.ManyToManyField(null=True, to='images.thumbnailsize')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accounttier'),
        ),
    ]
