# Generated by Django 4.1.7 on 2023-03-09 21:48

from django.db import migrations, models
import images.functions


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=images.functions.path_to_upload_img),
        ),
    ]
